# Generated by Django 4.1 on 2022-09-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customparameter',
            options={'verbose_name': '自定义参数', 'verbose_name_plural': '自定义参数'},
        ),
        migrations.AlterModelOptions(
            name='navbartab',
            options={'ordering': ['order'], 'verbose_name': '侧边栏标签', 'verbose_name_plural': '侧边栏标签'},
        ),
    ]
