# Generated by Django 4.1 on 2022-09-19 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grid', '0012_alter_profile_phone'),
        ('core', '0002_alter_customparameter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('o', '待处理'), ('x', '已结束')], default='o', max_length=1)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('approval_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='审批的用户', to=settings.AUTH_USER_MODEL)),
                ('mgrid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grid.microgrid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='申请的用户', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.village')),
            ],
            options={
                'verbose_name': '用户申请',
                'verbose_name_plural': '用户申请',
            },
        ),
    ]
