# Generated by Django 4.1 on 2022-09-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userapproval_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapproval',
            options={'permissions': [('can_deal_approvals', '处理用户申请的权限'), ('can_see_approvals', '查看用户申请的权限'), ('can_c/d_approvals', '创建/删除用户申请的权限')], 'verbose_name': '用户申请', 'verbose_name_plural': '用户申请'},
        ),
    ]
