# Generated by Django 4.1 on 2022-10-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userapproval_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customparameter',
            name='value',
            field=models.TextField(blank=True, help_text='参数值', max_length=1000, null=True),
        ),
    ]
