# Generated by Django 4.1 on 2022-08-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=8, null=True)),
                ('sort', models.IntegerField(blank=True, help_text='村内排序', null=True)),
                ('name', models.CharField(blank=True, help_text='网格名称', max_length=30, null=True)),
                ('houses', models.IntegerField(blank=True, help_text='网格内户数')),
                ('population', models.IntegerField(blank=True, help_text='网格内人口')),
                ('deleted', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='村名', max_length=20)),
                ('houses', models.IntegerField(blank=True, help_text='总户数')),
                ('mgrids', models.IntegerField(blank=True, help_text='总网格数')),
                ('population', models.IntegerField(blank=True, help_text='人口')),
                ('locationX', models.DecimalField(blank=True, decimal_places=6, help_text='百度地图坐标X', max_digits=9, null=True)),
                ('locationY', models.DecimalField(blank=True, decimal_places=6, help_text='百度地图坐标Y', max_digits=9, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgrid', models.ForeignKey(blank=True, help_text='用户所属的网格', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.microgrid')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(blank=True, help_text='用户所属的村庄', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.village')),
            ],
        ),
        migrations.AddField(
            model_name='microgrid',
            name='village',
            field=models.ForeignKey(blank=True, help_text='所属村庄', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.village'),
        ),
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=8, null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='CustomStaticsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='自定义统计标题', max_length=30)),
                ('range', models.CharField(choices=[('g', '所属微网格'), ('v', '村庄内所有微网格'), ('a', '全局')], help_text='统计范围', max_length=1)),
                ('datatype', models.CharField(choices=[('C', '文本'), ('B', '布尔（√或×）'), ('I', '数字（整数）'), ('F', '数字（带小数点）')], default='C', help_text='统计数据类型', max_length=1)),
                ('create_date', models.DateField(auto_now_add=True, help_text='创建日期')),
                ('closed', models.BooleanField(blank=True, default=False, help_text='关闭')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('mgrid', models.ForeignKey(blank=True, help_text='所属微网格（如果是微网格范围的统计）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.microgrid')),
                ('village', models.ForeignKey(blank=True, help_text='所属村庄（如果是村范围的统计）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.village')),
            ],
        ),
        migrations.CreateModel(
            name='CustomStaticsInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_char', models.CharField(blank=True, max_length=50, null=True)),
                ('data_bool', models.BooleanField(blank=True, null=True)),
                ('data_int', models.BigIntegerField(blank=True, null=True)),
                ('data_float', models.FloatField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.customstaticstemplate')),
            ],
        ),
    ]
