# Generated by Django 4.1 on 2022-08-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(blank=True, default='未命名村庄', help_text='村名', max_length=20),
        ),
    ]
