# Generated by Django 4.1 on 2022-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_alter_village_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(help_text='村名', max_length=20),
        ),
    ]
