# Generated by Django 4.1 on 2022-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_alter_village_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microgrid',
            name='houses',
            field=models.IntegerField(blank=True, default=0, help_text='网格内户数'),
        ),
        migrations.AlterField(
            model_name='microgrid',
            name='population',
            field=models.IntegerField(blank=True, default=0, help_text='网格内人口'),
        ),
    ]
