# Generated by Django 4.1 on 2022-08-15 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0007_alter_resident_idnumber'),
        ('grid', '0005_customstaticsinstance_resident_alter_microgrid_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstaticsinstance',
            name='resident',
            field=models.ForeignKey(help_text='统计对象', on_delete=django.db.models.deletion.CASCADE, to='resident.resident'),
        ),
    ]
