# Generated by Django 4.1 on 2022-09-01 05:26

from django.db import migrations, models
import django.db.models.deletion
import grid.models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0011_alter_house_mgrid_alter_house_village'),
        ('grid', '0006_alter_customstaticsinstance_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customstaticsinstance',
            name='data_bool',
        ),
        migrations.RemoveField(
            model_name='customstaticsinstance',
            name='data_char',
        ),
        migrations.RemoveField(
            model_name='customstaticsinstance',
            name='data_float',
        ),
        migrations.RemoveField(
            model_name='customstaticsinstance',
            name='data_int',
        ),
        migrations.RemoveField(
            model_name='customstaticstemplate',
            name='datatype',
        ),
        migrations.AddField(
            model_name='customstaticsinstance',
            name='data',
            field=models.JSONField(default=grid.models.example_data, help_text='统计数据的内容'),
        ),
        migrations.AddField(
            model_name='customstaticsinstance',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resident.house'),
        ),
        migrations.AddField(
            model_name='customstaticsinstance',
            name='mgrid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grid.microgrid'),
        ),
        migrations.AddField(
            model_name='customstaticstemplate',
            name='datatypes',
            field=models.JSONField(default=grid.models.example_datatypes, help_text='统计数据的内容'),
        ),
        migrations.AddField(
            model_name='customstaticstemplate',
            name='obj',
            field=models.CharField(choices=[('r', '人员'), ('h', '房屋'), ('g', '微网格')], default='r', help_text='统计对象', max_length=1),
        ),
        migrations.AlterField(
            model_name='customstaticsinstance',
            name='resident',
            field=models.ForeignKey(blank=True, help_text='统计对象', null=True, on_delete=django.db.models.deletion.CASCADE, to='resident.resident'),
        ),
        migrations.AlterField(
            model_name='customstaticstemplate',
            name='range',
            field=models.CharField(choices=[('v', '所属村庄'), ('g', '所属微网格'), ('a', '全局')], help_text='统计范围', max_length=1),
        ),
    ]
