# Generated by Django 4.1 on 2022-09-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0007_remove_customstaticsinstance_data_bool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customstaticstemplate',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, help_text='删除'),
        ),
    ]
