# Generated by Django 4.1 on 2022-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0008_customstaticstemplate_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customstaticsinstance',
            options={'verbose_name': '自定义统计实例', 'verbose_name_plural': '自定义统计实例'},
        ),
        migrations.AlterModelOptions(
            name='customstaticstemplate',
            options={'verbose_name': '自定义统计模板', 'verbose_name_plural': '自定义统计模板'},
        ),
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'verbose_name': '扩展用户组信息', 'verbose_name_plural': '扩展用户组信息'},
        ),
        migrations.AlterModelOptions(
            name='microgrid',
            options={'verbose_name': '微网格', 'verbose_name_plural': '微网格'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '扩展的用户信息', 'verbose_name_plural': '扩展的用户信息'},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'verbose_name': '村庄', 'verbose_name_plural': '村庄'},
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=0, help_text='用户的手机号，用于登录和重置密码'),
            preserve_default=False,
        ),
    ]
