# Generated by Django 4.1 on 2022-09-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0009_alter_customstaticsinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, help_text='用户的手机号，用于登录和重置密码', null=True),
        ),
    ]
