# Generated by Django 4.1 on 2022-09-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0018_alter_village_houses_alter_village_mgrids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='r_name',
            field=models.CharField(blank=True, help_text='真实姓名', max_length=20, null=True),
        ),
    ]
