# Generated by Django 4.1 on 2022-10-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0019_profile_r_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customstaticstemplate',
            options={'permissions': [('can_see_stemplate', '查看统计模板的权限'), ('can_cd_stemplate', '创建/删除统计模板的权限'), ('village_mark_stemplate', '统计模板权限的村管理员标记'), ('mgrid_mark_stemplate', '统计模板权限的网格管理员标记')], 'verbose_name': '自定义统计模板', 'verbose_name_plural': '自定义统计模板'},
        ),
    ]
