# Generated by Django 4.1 on 2022-08-12 16:16

from django.db import migrations, models
import django.db.models.deletion
import resident.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField(blank=True, help_text='人数', null=True)),
                ('mgridID', models.IntegerField(help_text='网格序号')),
                ('location1X', models.DecimalField(blank=True, decimal_places=6, help_text='百度地图坐标1X', max_digits=9, null=True)),
                ('location1Y', models.DecimalField(blank=True, decimal_places=6, help_text='百度地图坐标1Y', max_digits=9, null=True)),
                ('location2X', models.DecimalField(blank=True, decimal_places=6, help_text='百度地图坐标2X', max_digits=9, null=True)),
                ('location2Y', models.DecimalField(blank=True, decimal_places=6, help_text='百度地图坐标2Y', max_digits=9, null=True)),
                ('location3X', models.DecimalField(blank=True, decimal_places=6, help_text='百度地图坐标3X', max_digits=9, null=True)),
                ('location3Y', models.DecimalField(blank=True, decimal_places=6, help_text='百度地图坐标3Y', max_digits=9, null=True)),
                ('location4X', models.DecimalField(blank=True, decimal_places=6, help_text='百度地图坐标4X', max_digits=9, null=True)),
                ('location4Y', models.DecimalField(blank=True, decimal_places=6, help_text='百度地图坐标4Y', max_digits=9, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, help_text='删除')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=20)),
                ('IDnumber', models.CharField(max_length=18, unique=True, validators=[resident.models.IDValidator])),
                ('sex', models.CharField(blank=True, choices=[('m', '男'), ('f', '女'), ('o', '其他')], help_text='性别', max_length=1)),
                ('phone', models.BigIntegerField(blank=True, help_text='电话')),
                ('isLocalResident', models.BooleanField(default=False, help_text='是否常住')),
                ('outLocation', models.CharField(blank=True, help_text='在外地点', max_length=30, null=True)),
                ('note', models.CharField(blank=True, help_text='备注', max_length=100, null=True)),
                ('isholder', models.BooleanField(default=False, help_text='户主')),
                ('deleted', models.BooleanField(default=False, help_text='删除')),
                ('b_house', models.ForeignKey(blank=True, help_text='户', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resident.house')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='holder',
            field=models.OneToOneField(blank=True, help_text='户主', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resident.resident'),
        ),
        migrations.AddField(
            model_name='house',
            name='mgrid',
            field=models.ForeignKey(blank=True, help_text='所属网格', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.microgrid'),
        ),
        migrations.AddField(
            model_name='house',
            name='village',
            field=models.ForeignKey(blank=True, help_text='所属村', null=True, on_delete=django.db.models.deletion.SET_NULL, to='grid.village'),
        ),
    ]
