# Generated by Django 4.1 on 2022-08-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='phone',
            field=models.BigIntegerField(blank=True, help_text='电话', null=True),
        ),
    ]
