# Generated by Django 4.1 on 2022-08-13 08:03

from django.db import migrations, models
import resident.models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_alter_resident_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='IDnumber',
            field=models.CharField(max_length=18, validators=[resident.models.IDValidator]),
        ),
    ]
