# Generated by Django 4.1 on 2022-08-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_alter_resident_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='population',
            field=models.IntegerField(blank=True, default=0, help_text='人数', null=True),
        ),
    ]
