# Generated by Django 4.1 on 2022-08-14 13:50

from django.db import migrations, models
import resident.models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0005_alter_resident_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='IDnumber',
            field=models.CharField(blank=True, help_text='身份证', max_length=18, validators=[resident.models.IDValidator]),
        ),
    ]
