# Generated by Django 4.1 on 2022-08-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0007_alter_resident_idnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='location1X',
        ),
        migrations.RemoveField(
            model_name='house',
            name='location1Y',
        ),
        migrations.RemoveField(
            model_name='house',
            name='location2X',
        ),
        migrations.RemoveField(
            model_name='house',
            name='location2Y',
        ),
        migrations.RemoveField(
            model_name='house',
            name='location3X',
        ),
        migrations.RemoveField(
            model_name='house',
            name='location3Y',
        ),
        migrations.RemoveField(
            model_name='house',
            name='location4X',
        ),
        migrations.RemoveField(
            model_name='house',
            name='location4Y',
        ),
    ]
