# Generated by Django 4.1 on 2022-08-23 16:30

from django.db import migrations, models
import resident.models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0008_remove_house_location1x_remove_house_location1y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='geo',
            field=models.JSONField(default=resident.models.default_geo_data, help_text='房屋的地图数据'),
        ),
    ]
