# Generated by Django 4.1 on 2022-08-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0006_alter_customstaticsinstance_resident'),
        ('resident', '0010_alter_house_mgridid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='mgrid',
            field=models.ForeignKey(default=0, help_text='所属网格', on_delete=django.db.models.deletion.CASCADE, to='grid.microgrid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='village',
            field=models.ForeignKey(default=0, help_text='所属村', on_delete=django.db.models.deletion.CASCADE, to='grid.village'),
            preserve_default=False,
        ),
    ]
