# Generated by Django 4.1 on 2022-09-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0011_alter_house_mgrid_alter_house_village'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': '住户信息', 'verbose_name_plural': '住户信息'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': '人员信息', 'verbose_name_plural': '人员信息'},
        ),
    ]
