# Generated by Django 4.1 on 2022-10-10 04:01

from django.db import migrations, models
import resident.models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0015_alter_house_options_alter_resident_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='r_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='IDnumber',
            field=models.CharField(blank=True, help_text='身份证', max_length=18, null=True, validators=[resident.models.IDValidator]),
        ),
    ]
