# Generated by Django 4.1 on 2022-08-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resident', '0001_initial'),
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=30)),
                ('behaviour', models.CharField(choices=[('c', '创建'), ('u', '编辑'), ('d', '删除')], max_length=1)),
                ('changetime', models.DateTimeField(auto_now_add=True)),
                ('changeby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grid.village')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=30)),
                ('behaviour', models.CharField(choices=[('c', '创建'), ('u', '编辑'), ('d', '删除')], max_length=1)),
                ('changetime', models.DateTimeField(auto_now_add=True)),
                ('changeby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.resident')),
            ],
        ),
        migrations.CreateModel(
            name='MicroGridChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=30)),
                ('behaviour', models.CharField(choices=[('c', '创建'), ('u', '编辑'), ('d', '删除')], max_length=1)),
                ('changetime', models.DateTimeField(auto_now_add=True)),
                ('changeby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grid.microgrid')),
            ],
        ),
        migrations.CreateModel(
            name='HouseChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=30)),
                ('behaviour', models.CharField(choices=[('c', '创建'), ('u', '编辑'), ('d', '删除')], max_length=1)),
                ('changetime', models.DateTimeField(auto_now_add=True)),
                ('changeby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resident.house')),
            ],
        ),
        migrations.CreateModel(
            name='CustomStaticsTemplateChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=30)),
                ('behaviour', models.CharField(choices=[('c', '创建'), ('u', '编辑'), ('d', '删除')], max_length=1)),
                ('changetime', models.DateTimeField(auto_now_add=True)),
                ('changeby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grid.customstaticstemplate')),
            ],
        ),
        migrations.CreateModel(
            name='CustomStaticsInstanceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=30)),
                ('behaviour', models.CharField(choices=[('c', '创建'), ('u', '编辑'), ('d', '删除')], max_length=1)),
                ('changetime', models.DateTimeField(auto_now_add=True)),
                ('changeby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grid.customstaticsinstance')),
            ],
        ),
    ]
