# Generated by Django 4.1 on 2022-08-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customstaticsinstancechangelog',
            name='context',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customstaticstemplatechangelog',
            name='context',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='housechangelog',
            name='context',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='microgridchangelog',
            name='context',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='residentchangelog',
            name='context',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='villagechangelog',
            name='context',
            field=models.CharField(max_length=500),
        ),
    ]
