# Generated by Django 4.1 on 2022-09-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_userloginlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='device_name',
            field=models.CharField(max_length=300),
        ),
    ]
