# Generated by Django 4.1 on 2022-09-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_userloginlog_device_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customstaticsinstancechangelog',
            options={'verbose_name': '自定义统计实例变更日志', 'verbose_name_plural': '自定义统计实例变更日志'},
        ),
        migrations.AlterModelOptions(
            name='customstaticstemplatechangelog',
            options={'verbose_name': '自定义统计模板变更日志', 'verbose_name_plural': '自定义统计模板变更日志'},
        ),
        migrations.AlterModelOptions(
            name='housechangelog',
            options={'verbose_name': '住户变更日志', 'verbose_name_plural': '住户变更日志'},
        ),
        migrations.AlterModelOptions(
            name='microgridchangelog',
            options={'verbose_name': '微网格变更日志', 'verbose_name_plural': '微网格变更日志'},
        ),
        migrations.AlterModelOptions(
            name='residentchangelog',
            options={'verbose_name': '人员变更日志', 'verbose_name_plural': '人员变更日志'},
        ),
        migrations.AlterModelOptions(
            name='userloginlog',
            options={'verbose_name': '用户登录日志', 'verbose_name_plural': '用户登录日志'},
        ),
        migrations.AlterModelOptions(
            name='villagechangelog',
            options={'verbose_name': '村庄变更日志', 'verbose_name_plural': '村庄变更日志'},
        ),
    ]
