# Generated by Django 4.1 on 2022-09-17 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0005_alter_customstaticsinstancechangelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='device_name',
            field=models.CharField(max_length=300, verbose_name='设备名称'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='ip_address',
            field=models.CharField(max_length=20, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
